baseURL = "https://baduk.com.br/"
locale = "pt-BR"
title = "Baduk - Aprenda a jogar Go Interativamente"

enableRobotsTXT = "true"
disableKinds = ["taxonomy"]

[sitemap]
  ChangeFreq = "weekly"
  Priority = ".5"

[params]

  [params.main]
    name = "Tutorial"
    description = "Aprenda Go passo a passo"

  [params.tsumego]
    name = "Problemas de Go"
    description = "Exercícios para praticar"

  [params.theory]
    name = "Conceitos Avançados"
    description = "Estratégias e teoria"

  [params.matches]
    name = "Partidas Famosas"
    description = "Jogos do AlphaGo e análises"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
