#!/usr/bin/env python3
import os
import re

def final_cleanup(content):
    """Limpeza final de palavras em inglês restantes"""
    
    # Traduções específicas para palavras comuns restantes
    translations = {
        # Artigos e preposições
        " the ": " o ",
        " a ": " um ",
        " an ": " um ",
        " and ": " e ",
        " or ": " ou ",
        " in ": " em ",
        " on ": " em ",
        " at ": " em ",
        " to ": " para ",
        " for ": " para ",
        " of ": " de ",
        " with ": " com ",
        " by ": " por ",
        " from ": " de ",
        " up ": " para cima ",
        " about ": " sobre ",
        " into ": " em ",
        " through ": " através de ",
        " during ": " durante ",
        " before ": " antes de ",
        " after ": " depois de ",
        " above ": " acima de ",
        " below ": " abaixo de ",
        " between ": " entre ",
        " among ": " entre ",
        " under ": " sob ",
        " over ": " sobre ",
        " around ": " ao redor de ",
        " near ": " perto de ",
        " far ": " longe de ",
        " here ": " aqui ",
        " there ": " lá ",
        " where ": " onde ",
        " when ": " quando ",
        " why ": " por que ",
        " how ": " como ",
        " what ": " o que ",
        " who ": " quem ",
        " which ": " qual ",
        " that ": " que ",
        " this ": " isto ",
        " these ": " estes ",
        " those ": " aqueles ",
        " some ": " alguns ",
        " any ": " qualquer ",
        " all ": " todos ",
        " every ": " cada ",
        " each ": " cada ",
        " both ": " ambos ",
        " either ": " qualquer um ",
        " neither ": " nenhum ",
        " one ": " um ",
        " two ": " dois ",
        " three ": " três ",
        " four ": " quatro ",
        " five ": " cinco ",
        " six ": " seis ",
        " seven ": " sete ",
        " eight ": " oito ",
        " nine ": " nove ",
        " ten ": " dez ",
        " first ": " primeiro ",
        " second ": " segundo ",
        " third ": " terceiro ",
        " last ": " último ",
        " next ": " próximo ",
        " previous ": " anterior ",
        " other ": " outro ",
        " another ": " outro ",
        " same ": " mesmo ",
        " different ": " diferente ",
        " good ": " bom ",
        " bad ": " ruim ",
        " better ": " melhor ",
        " best ": " melhor ",
        " worse ": " pior ",
        " worst ": " pior ",
        " big ": " grande ",
        " small ": " pequeno ",
        " large ": " grande ",
        " little ": " pouco ",
        " long ": " longo ",
        " short ": " curto ",
        " high ": " alto ",
        " low ": " baixo ",
        " new ": " novo ",
        " old ": " velho ",
        " young ": " jovem ",
        " hot ": " quente ",
        " cold ": " frio ",
        " warm ": " morno ",
        " cool ": " fresco ",
        " fast ": " rápido ",
        " slow ": " lento ",
        " quick ": " rápido ",
        " easy ": " fácil ",
        " hard ": " difícil ",
        " difficult ": " difícil ",
        " simple ": " simples ",
        " complex ": " complexo ",
        " important ": " importante ",
        " necessary ": " necessário ",
        " possible ": " possível ",
        " impossible ": " impossível ",
        " true ": " verdadeiro ",
        " false ": " falso ",
        " real ": " real ",
        " fake ": " falso ",
        " right ": " certo ",
        " wrong ": " errado ",
        " correct ": " correto ",
        " incorrect ": " incorreto ",
        " yes ": " sim ",
        " no ": " não ",
        " maybe ": " talvez ",
        " perhaps ": " talvez ",
        " sure ": " certo ",
        " certain ": " certo ",
        " uncertain ": " incerto ",
        " clear ": " claro ",
        " unclear ": " não claro ",
        " obvious ": " óbvio ",
        " hidden ": " escondido ",
        " visible ": " visível ",
        " invisible ": " invisível ",
        " open ": " aberto ",
        " closed ": " fechado ",
        " free ": " livre ",
        " busy ": " ocupado ",
        " available ": " disponível ",
        " unavailable ": " indisponível ",
        " ready ": " pronto ",
        " not ready ": " não pronto ",
        " finished ": " terminado ",
        " unfinished ": " não terminado ",
        " complete ": " completo ",
        " incomplete ": " incompleto ",
        " full ": " cheio ",
        " empty ": " vazio ",
        " half ": " metade ",
        " whole ": " todo ",
        " part ": " parte ",
        " piece ": " pedaço ",
        " bit ": " pouco ",
        " lot ": " muito ",
        " many ": " muitos ",
        " much ": " muito ",
        " few ": " poucos ",
        " little ": " pouco ",
        " more ": " mais ",
        " less ": " menos ",
        " most ": " mais ",
        " least ": " menos ",
        " enough ": " suficiente ",
        " too much ": " demais ",
        " too little ": " muito pouco ",
        " very ": " muito ",
        " quite ": " bastante ",
        " rather ": " bastante ",
        " pretty ": " bastante ",
        " really ": " realmente ",
        " actually ": " na verdade ",
        " finally ": " finalmente ",
        " eventually ": " eventualmente ",
        " immediately ": " imediatamente ",
        " soon ": " em breve ",
        " later ": " mais tarde ",
        " early ": " cedo ",
        " late ": " tarde ",
        " now ": " agora ",
        " then ": " então ",
        " today ": " hoje ",
        " yesterday ": " ontem ",
        " tomorrow ": " amanhã ",
        " always ": " sempre ",
        " never ": " nunca ",
        " sometimes ": " às vezes ",
        " often ": " frequentemente ",
        " rarely ": " raramente ",
        " usually ": " usualmente ",
        " normally ": " normalmente ",
        " typically ": " tipicamente ",
        " generally ": " geralmente ",
        " specifically ": " especificamente ",
        " particularly ": " particularmente ",
        " especially ": " especialmente ",
        " mainly ": " principalmente ",
        " mostly ": " principalmente ",
        " partly ": " parcialmente ",
        " completely ": " completamente ",
        " totally ": " totalmente ",
        " absolutely ": " absolutamente ",
        " relatively ": " relativamente ",
        " approximately ": " aproximadamente ",
        " exactly ": " exatamente ",
        " precisely ": " precisamente ",
        " roughly ": " aproximadamente ",
        " about ": " sobre ",
        " around ": " ao redor de ",
        " nearly ": " quase ",
        " almost ": " quase ",
        " quite ": " bastante ",
        " rather ": " bastante ",
        " pretty ": " bastante ",
        " very ": " muito ",
        " extremely ": " extremamente ",
        " incredibly ": " incrivelmente ",
        " amazingly ": " surpreendentemente ",
        " surprisingly ": " surpreendentemente ",
        " unfortunately ": " infelizmente ",
        " fortunately ": " felizmente ",
        " luckily ": " felizmente ",
        " unluckily ": " infelizmente ",
        " hopefully ": " esperançosamente ",
        " hopelessly ": " desesperadamente ",
        " definitely ": " definitivamente ",
        " probably ": " provavelmente ",
        " possibly ": " possivelmente ",
        " certainly ": " certamente ",
        " surely ": " certamente ",
        " obviously ": " obviamente ",
        " clearly ": " claramente ",
        " apparently ": " aparentemente ",
        " evidently ": " evidentemente ",
        " supposedly ": " supostamente ",
        " allegedly ": " alegadamente ",
        " reportedly ": " supostamente ",
        
        # Palavras específicas que aparecem nos exemplos
        " separated ": " separadas ",
        " thé ": " isto ",
        " é ": " é ",
        " good ": " bom ",
        " result ": " resultado ",
        " para ": " para ",
        " preto ": " preto ",
        " stone ": " pedra ",
        " at ": " em ",
        " still ": " ainda ",
        " tem ": " tem ",
        " aji ": " aji ",
        " isn't ": " não é ",
        " too ": " muito ",
        " bad ": " ruim ",
        " mas ": " mas ",
        " Black ": " Preto ",
        " pode ": " pode ",
        " obter ": " obter ",
        " better ": " melhor ",
        " with ": " com ",
        " sharper ": " mais afiado ",
        " play ": " jogada ",
        " usually ": " usualmente ",
        " needs ": " precisa ",
        " three ": " três ",
        " liberties ": " liberdades ",
        " make ": " fazer ",
        " work ": " funcionar ",
        " mas ": " mas ",
        " he ": " ele ",
        " only ": " apenas ",
        " has ": " tem ",
        " two ": " dois ",
        " dead ": " morto ",
        " stone ": " pedra ",
        " been ": " foi ",
        " wasted ": " desperdiçada ",
        " fazer ": " fazer ",
        " melhor ": " melhor ",
        " sometimes ": " às vezes ",
        " something ": " algo ",
        " like ": " como ",
        " this ": " isto ",
        " mas ": " mas ",
        " can ": " pode ",
        " do ": " fazer ",
        " much ": " muito ",
        " better ": " melhor ",
        " in ": " em ",
        " situation ": " situação ",
        " also ": " também ",
        " possible ": " possível ",
        " mas ": " mas ",
        " make ": " fazer ",
        " profitable ": " lucrativo ",
        " forcing ": " forçando ",
        " exchange ": " troca ",
        " before ": " antes de ",
        " connecting ": " conectar ",
        " If ": " Se ",
        " joga ": " joga ",
        " later ": " mais tarde ",
        " on ": " em ",
        " will ": " vai ",
        " be ": " ser ",
        " more ": " mais ",
        " likely ": " provável ",
        " to ": " para ",
        " ignore ": " ignorar ",
        " it ": " isto ",
        " now ": " agora ",
        " should ": " deveria ",
        " avoid ": " evitar ",
        " cut ": " corte ",
        " viver ": " viver ",
        " corner ": " canto ",
        " mas ": " mas ",
        " o ": " o ",
        " corte ": " corte ",
        " do ": " do ",
        " pretoting ": " pretas ",
        " stones ": " pedras ",
        " are ": " são ",
        " lonely ": " solitárias ",
        " now ": " agora ",
    }
    
    # Aplicar traduções
    for english, portuguese in translations.items():
        content = content.replace(english, portuguese)
    
    return content

def process_sgf_file(file_path):
    """Processa um arquivo SGF"""
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Verificar se tem palavras em inglês não traduzidas
    if re.search(r'\b(the|a|an|and|or|in|on|at|to|for|of|with|by|from|up|about|into|through|during|before|after|above|below|between|among|under|over|around|near|far|here|there|where|when|why|how|what|who|which|that|this|these|those|some|any|all|every|each|both|either|neither|one|two|three|four|five|six|seven|eight|nine|ten|first|second|third|last|next|previous|other|another|same|different|good|bad|better|best|worse|worst|big|small|large|little|long|short|high|low|new|old|young|hot|cold|warm|cool|fast|slow|quick|easy|hard|difficult|simple|complex|important|necessary|possible|impossible|true|false|real|fake|right|wrong|correct|incorrect|yes|no|maybe|perhaps|sure|certain|uncertain|clear|unclear|obvious|hidden|visible|invisible|open|closed|free|busy|available|unavailable|ready|not ready|finished|unfinished|complete|incomplete|full|empty|half|whole|part|piece|bit|lot|many|much|few|little|more|less|most|least|enough|too much|too little|very|quite|rather|pretty|really|actually|finally|eventually|immediately|soon|later|early|late|now|then|today|yesterday|tomorrow|always|never|sometimes|often|rarely|usually|normally|typically|generally|specifically|particularly|especially|mainly|mostly|partly|completely|totally|absolutely|relatively|approximately|exactly|precisely|roughly|about|around|nearly|almost|quite|rather|pretty|very|extremely|incredibly|amazingly|surprisingly|unfortunately|fortunately|luckily|unluckily|hopefully|hopelessly|definitely|probably|possibly|certainly|surely|obviously|clearly|apparently|evidently|supposedly|allegedly|reportedly|separated|thé|é|good|result|para|preto|stone|at|still|tem|aji|isn't|too|bad|mas|Black|pode|obter|better|with|sharper|play|usually|needs|three|liberties|make|work|he|only|has|two|dead|been|wasted|fazer|melhor|sometimes|something|like|this|can|do|much|in|situation|also|possible|make|profitable|forcing|exchange|before|connecting|If|joga|later|on|will|be|more|likely|to|ignore|it|now|should|avoid|cut|viver|corner|o|corte|do|pretoting|stones|are|lonely)\b', content, re.IGNORECASE):
        print(f'Fazendo limpeza final em {file_path}...')
        content = final_cleanup(content)
        
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
        return True
    return False

def main():
    base_dir = 'content/sgfs/tsumego'
    fixed_count = 0
    
    # Processar todos os arquivos SGF
    for filename in os.listdir(base_dir):
        if filename.endswith('.sgf'):
            file_path = os.path.join(base_dir, filename)
            if process_sgf_file(file_path):
                fixed_count += 1
    
    print(f'Limpeza final concluída em {fixed_count} arquivos')

if __name__ == '__main__':
    main()
